<html>
<head>
</head>
<body>


<?php

echo "<div id='news'>";
$i=1;
if(!count($this->news)) echo "<h3>No news</h3>";

foreach($this->news as $line)
{
    if($i%2 == 0) echo "<article class='artr'>";
    else echo "<article class='artl'>";

    echo "<table>
    <tr>
    <td>
    <header class='title'>".$line['title']."</header>
    </td>
    </tr>
    <tr>
    <td>
    <img class='image' src='".$this->baseUrl()."/pg/img/news/".$line['image']."'/>
    </td>
    <td>
    <p class='description'>".$line['description']."</p>
    </td>
    </tr>
    </table>
    </article>";
    $i++;
}
echo "</div>";

$sql = new Application_Model_SQL();
$numPages = $sql->newsNumber();
$page = $this->page;

echo "<div class='pagination'><table><tr>";
if($page-1 > 0)
{
    echo "<td><a href=".$this->url(array('controller'=>'index','action'=>'index','page' => $page-1))."> Anterior </a></td>";
}

for($j=1; $j<=$numPages; $j++)
{

    if($j != $page)
        echo "<td><a href=".$this->url(array('controller'=>'index','action'=>'index','page' => $j)).">".$j."</a></td>";

    else
    {
        echo "<td> ".$j." </td>";
    }
}

if($page!=$numPages)
{
    echo "<td><a href=".$this->url(array('controller'=>'index','action'=>'index','page' => $page+1))."> Siguiente </a></td>";

}

echo "</tr></table></div>";

?>

</body>
</html>