<html>
<head>
<body>  
 <div id='news'>
        
    <?php 

    $i=1;
    if(!count($this->news)) echo "<h3>No news</h3>";
	foreach($this->news as $line)
        {
	    if($i%2 == 0) echo "<article class='artr'>";
            else echo "<article class='artl'>";
	    echo "<table>
	    <tr> 
		<td> 
		    <header class='title'>".$line['title']."</header> 
		</td> 
	    </tr>
	    <tr> 
		<td> 
		    <img class='image' src='".$line['image']."'/> 
		</td>
		<td> 
		    <p class='description'>".$line['description']."</p>
		</td>
	    </tr>
	    </table>
	    </article>";
	    $i++;
        }
    ?>
 </div>
</body>
</head>
</html>