<html>
<head>
</head>
<body>
<div id='users'>
        <table>
        <tr>
        <td>Usuario</td>
        <td>Nombre</td>
        <td>Apellido</td>
        <td></td>
        <td></td>
	<td></td>
        </tr>
        <?php

        foreach($this->user as $line)
{
    echo "<tr>
    <td>".$line['cc']."</td>
    <td>".$line['names']."</td>
    <td>".$line['lastnames']."</td>
    <td><a href=".$this->url(array('controller'=>'index', 'action'=>'update-user','usr'=>$this->userType,'cc'=>$line['cc'])).">Editar Datos</a></td>
    <td><a href=".$this->url(array('controller'=>'index', 'action'=>'update-password','usr'=>$this->userType,'cc'=>$line['cc'])).">Editar Contraseña</a></td>
    <td><a href=".$this->url(array('controller'=>'index', 'action'=>'delete-user','usr'=>$this->userType,'cc'=>$line['cc'])).">Borrar</a></td>
    </tr>";
}
?>
</table>
</div>
</body>
</html>