<html>
<head>
</head>
<body>

<?php
$sql = new Application_Model_SQL();

if($this->memos == 1)
{
    echo "<div id='editMemo'>
    <table>
    <tr>
    <td>Titulo</td>
    <td></td>
    <td></td>
    </tr>";

    foreach($sql->listMemos($this->user) as $line)
    {
        echo "<tr>
        <td>".$line['title']."</td>
        <td><a href=".$this->url(array('controller'=>'index', 'action'=>'update-memo','memo'=>$line['id'],'cc'=>$this->user)).">Editar</a></td>
        <td><a href=".$this->url(array('controller'=>'index', 'action'=>'delete-memo','memo'=>$line['id'])).">Borrar</a></td>
        </tr>";
    }
    echo "</table>";
}
elseif($this->memos == 0)
{
    foreach($sql->listMemos($this->user) as $line)
    {
        echo "<div class='listmemo'>
        <table>
        <tr>
        <td>".$line['title']."</td>
        </tr>
        <tr>
        <td>".$line['description']."</td>
        </tr>
        </table>
        </div>";

    }
}
?>
</div>
</body>
</html>