<div id='news'>
<?php
if(!count($this->news))
    echo "No hay noticias.";
else
{
?>
  <table class='tbupdate'>
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Cabecera</th>
        <th>Descripción</th>
        <th colspan='2'>Acciones</th>
      </tr>
    </thead>
    <tbody>
    <?php

    foreach($this->news as $news)
    {
        echo "<tr><td>".$news['title']."</td><td>".$news['header']."</td><td>".$news['description']."</td><td><a href=".$this->url(array('controller'=>'news', 'action'=>'update','news'=>$news['id'])).">Editar</a></td><td><a href=".$this->url(array('controller'=>'news', 'action'=>'delete','news'=>$news['id'])).">Borrar</a></td></tr>";
    }
    ?>
    </tbody>
  </table>
<?php
}
?>
</div>

