<div id='services'>

<?php

if(!count($this->services))
    echo "No hay servicios registrados.";
else
{
    foreach($this->services as $service)
    {
        echo "<br><article class='card'>";
        echo "<header class='title'>$service->name</header>";
        echo "<img class='default' src='".$this->url(array('controller'=>'index', 'action'=>'view', 'i'=>$service->id_image))."' />";
        echo "<p>$service->description</p>";
        echo "<div class='clear'></div></article>";
    }
}

?>
</div>
<br>
