<?php
if(!count($this->services))
    echo "No hay servicios registrados.";
else
{
    foreach($this->services as $service)
    {
        ?>
        <article>
          <header class='title'>
            <?php echo $service->name; ?>
          </header>
            <img src='<?php echo $this->url(array('controller'=>'index', 'action'=>'view', 'i'=>$service->id_image)); ?>' />
            <p><?php echo $service->description; ?></p>
        </article>
        <?php
    }
}
