<div id='proyect'>
<?php

$i=1;
if(!count($this->proyects))
    echo "No hay proyectos registrados.";
else
{
    foreach($this->proyects as $proyect)
    {
        if($i%2 == 0)
            echo "<article class='artr'>";
        else
            echo "<article class='artl'>";
?>
  <table>
    <tr>
      <td>
        <header class='name'><?php echo $proyect->name; ?></header>
      </td>
    </tr>
    <tr>
      <td>
        <img class='image' src='<?php echo $this->url(array('controller'=>'index', 'action'=>'view', 'i'=>$proyect->id_image)); ?>'/>
      </td>
      <td>
        <p class='description'><?php echo $proyect->description; ?></p>
      </td>
    </tr>
  </table>
</article>
<?php
        $i++;
    }
}
?>
</div>
