<div id='proyect'>
<?php

if(!count($this->proyects))
    echo "No hay proyectos registrados.";
else
{
    foreach($this->proyects as $proyect)
    {
        echo "<br><article class='card'>";
        echo "<header class='title'>$proyect->name</header>";
        echo "<img class='default' src='".$this->url(array('controller'=>'index', 'action'=>'view', 'i'=>$proyect->id_image))."' />";
        echo "<p>$proyect->description</p>";
        echo "<div class='clear'></div></article>";
    }
}
?>
</div>
<br>
