<?php
if(!count($this->proyects))
    echo "No hay proyectos registrados.";
else
{
?>
<table class='tbupdate'>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th colspan='2'>Acciones</th>
    </tr>
  </thead>
  <tbody>
  <?php
    foreach($this->proyects as $proyect)
        echo "<tr><td>".$proyect->name."</td><td>".$proyect->description."</td></td><td><a href='".$this->url(array('controller'=>'products', 'action'=>'update','p'=>$proyect->id))."'>Editar</a></td><td><a href='".$this->url(array('controller'=>'products', 'action'=>'delete','p'=>$proyect->id))."'>Borrar</a></td></tr>";
  ?>
</tbody>
</table>
<?php
}
