<div id='listInfo'>

<?php

if(!count($this->info))
    echo "No hay información.";
else
{
?>
<table>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    </tr>
    <?php
    foreach($this->info as $line)
    {
        echo "<tr>
        <td>".$line['title']."</td>
        <td><a href=".$this->url(array('controller'=>'who', 'action'=>'update','info'=>$line['id'])).">Editar</a></td>
        <td><a href=".$this->url(array('controller'=>'who', 'action'=>'delete','info'=>$line['id'])).">Borrar</a></td>
        </tr>";
    }
    ?>
</table>
<?php
}
