<div id='listInfo'>
<?php
if(!count($this->info))
    echo "No hay información.";
else
{
?>
  <table class='tbupdate'>
    <thead>
      <tr>
        <th>Título</th>
        <th>Descripción</th>
        <th colspan='2'>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($this->info as $info)
          echo "<tr><td>".$info['title']."</td><td>".$info['description']."</td><td><a href=".$this->url(array('controller'=>'who', 'action'=>'update','info'=>$info['id'])).">Editar</a></td><td><a href=".$this->url(array('controller'=>'who', 'action'=>'delete','info'=>$info['id'])).">Borrar</a></td></tr>";
      ?>
    </tbody>
  </table>
<?php
}
