<?php
echo $this->doctype("HTML5");
?>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php
    echo $this->headMeta();
    echo $this->headScript();
    echo $this->headLink()->appendStylesheet($this->baseUrl().'/global.css');
    echo $this->headLink(array('rel' => 'icon', 'href' => $this->baseUrl().'/img/favicon.png','type' => 'image/x-icon'));
    $this->headTitle()->prepend('GfifDev - ');
    echo $this->headTitle();
    $auth = Zend_Auth::getInstance();
    if ( $auth->hasIdentity())
    {
	echo "<li>Usuario: ".$auth->getIdentity()."</li>
	      <li><a href='".$this->url(array("controller" => "index", "action" => "logout"))."'>Logout</a>";
    }
    else
    {
	echo "<li><a href='".$this->url(array("controller" => "index", "action" => "index"))."'>Login</a>";
    }

  ?>
<!--     <script type="application/x-javascript" src="main.php"></script> -->
  </head>
  <body>
    <header id="hdppal"></header>
  <ul id="menu">
    <li><a href="<?php echo $this->url(array("controller" => "index", "action" => "index")); ?>">Inicio</a></li>
    <li><a href="<?php echo $this->url(array("controller" => "who", "action" => "index")); ?>">¿Quiénes somos?</a></li>
    <li>Productos</li>
    <li><a href="<?php echo $this->url(array("controller" => "services", "action" => "index")); ?>">Servicios</a></li>
    <li>Entrenamiento</li>
    <li>Open Source</li>
    <li>Contáctenos</li>
  </ul>
    <div id="content"><?php echo $this->layout()->content; ?><div class="clear"></div></div>
    <footer id="ftppal">Copyright © 2011 GfifDev S.A.S. Todos los derechos reservados.</footer>
  </body>
</html>
