<?php
echo $this->doctype("HTML5");
?>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--     <script type="application/x-javascript" src="main.php"></script> -->
  <?php
    echo $this->headMeta();
    echo $this->headScript();

    $this->headLink(array('rel' => 'icon', 'href' => $this->baseUrl().'/img/favicon.png','type' => 'image/x-icon'));
    echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/global.css');

    $this->headTitle()->prepend('GfifDev - ');
    echo $this->headTitle();
  ?>
  </head>
  <body>
<?php

    $auth = Zend_Auth::getInstance();
    $session = new Zend_Session_Namespace('Users');

    if($auth->hasIdentity())
    {
        $tbUser = new TbUser();
        $datos = $tbUser->find($auth->getIdentity());
        $datos = $datos[0];

        echo "<div id=\"\">Perfil: <a href='".$this->url(array("controller" => "user", "action" => "profile"), null, true)."'>".$datos['names']." ".$datos['lastnames']."</a></div>";
        echo "<div id=\"\"><a href='".$this->url(array("controller" => "user", "action" => "logout"))."'>Logout</a></div>";
    }

?>

    <header class="ppal">
      <a href="<?php echo $this->baseUrl(); ?>"><img class="img-logo" src="<?php echo $this->baseUrl()."/img/logo.png"; ?>"></img></a>
      <ul id="menu-ppal">
        <li class="menu-ppal-item"><a href="<?php echo $this->url(array("controller" => "who", "action" => "index"), null, true); ?>">¿Quiénes somos?</a></li>
        <li class="menu-ppal-item"><a href="<?php echo $this->url(array("controller" => "products", "action" => "index"), null, true); ?>">Productos</a></li>
        <li class="menu-ppal-item"><a href="<?php echo $this->url(array("controller" => "services", "action" => "index"), null, true); ?>">Servicios</a></li>
      </ul>
      <div class="hline"></div>
    </header>
    <div class="ppal"><?php echo $this->layout()->content; ?></div>
    <div class="hline"></div>
    <footer class="ppal">Copyright © 2012 GfifDev S.A.S. Todos los derechos reservados.</footer>
  </body>
</html>
