<div id='proyect'>
<?php

$i=1;

if(!count($this->proyect))
    echo "<h3>No Proyects</h3>";
else
{
    foreach($this->proyect as $line)
    {
        if($i%2 == 0)
            echo "<article class='artr'>";
        else
            echo "<article class='artl'>";
?>
  <table>
    <tr>
      <td>
        <header class='name'>".$line['name']."</header>
      </td>
    </tr>
    <tr>
      <td>
        <img class='image' src='".$this->baseUrl()."/pg/img/proy/".$line['image']."'/>
      </td>
      <td>
        <p class='description'>".$line['description']."</p>
      </td>
    </tr>
  </table>
</article>
<?php
        $i++;
    }
}
?>
</div>
