<?php
if(!count($this->users))
    echo "No hay usuarios registrados";
else
?>
<div id='users'>
  <table class='tbupdate'>
    <thead>
      <tr>
        <th>CC</td>
        <th>Nombre</td>
        <th>Apellido</td>
        <th>Teléfono</td>
        <th>Celular</td>
        <th colspan='2'>Acciones</td>
      </tr>
    </thead>
    <tbody>
    <?php
      foreach($this->users as $user)
          echo "<tr><td>".$user['cc']."</td><td>".$user['names']."</td><td>".$user['lastnames']."</td><td>".$user['telephone']."</td><td>".$user['movil']."</td><td><a href=".$this->url(array('controller'=>'user', 'action'=>'update','cc'=>$user['cc'])).">Editar</a></td><td><a href=".$this->url(array('controller'=>'user', 'action'=>'delete','cc'=>$user['cc'])).">Borrar</a></td></tr>";
    ?>
    </tbody>
  </table>
</div>
