<html>
  <head>
  </head>
  <body>
    <div id='users'>
      <table>
        <tr>
          <td>Usuario</td>
          <td>Nombre</td>
          <td>Apellido</td>
          <td></td>
          <td></td>
        </tr>
        <?php
        foreach($this->user as $line)
        {
            echo "<tr>
            <td>".$line['cc']."</td>
            <td>".$line['names']."</td>
            <td>".$line['lastnames']."</td>
            <td><a href=".$this->url(array('controller'=>'user', 'action'=>'update-user','type'=>$this->userType,'cc'=>$line['cc'])).">Editar</a></td>
            <td><a href=".$this->url(array('controller'=>'user', 'action'=>'delete-user','cc'=>$line['cc'])).">Borrar</a></td>
            </tr>";
        }
        ?>
      </table>
    </div>
  </body>
</html>
